### ISSUE TITLE
Please write documentation in form of simple README.md file and Repo. Description.

### ISSUE THREAD

**Issue by s-m-quadri** [Tejas-Dalvi-99/DecentralizedDonation#1]
# Why?

:+1: Although the name of the project **says what it does**. 

But to be specific, it's good practice to write **at least one paragraph** of description in Repo. Description and in README.md

**Comment by Tejas-Dalvi-99** [comment]
Hey @s-m-quadri , Thanks for the suggestions. I'll look into it !

**Comment by Tejas-Dalvi-99** [comment]
Updated README.md

**Comment by s-m-quadri** [comment]
:+1: **Nice!** You got it!
